import "./globals.css";
import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});
const playfair_display = Playfair_Display({
    subsets: ["latin"],
    variable: "--font-playfair-display",
});

export const metadata: Metadata = {
    title: "Skriemelis-Next",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            {/* <body className={inter.className}>{children}</body> */}
            <body
                className={`${inter.className} ${inter.variable} ${playfair_display.variable}`}
            >
                {children}
            </body>
        </html>
    );
}
