import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import { cn } from "@/lib/utils";

import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from "@clerk/nextjs";

import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});
const playfair_display = Playfair_Display({
    subsets: ["latin"],
    variable: "--font-playfair-display",
});

export const metadata: Metadata = {
    title: "Skriemelis-Next",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            {/* <html lang="en"> */}
            <html lang="en" className="dark">
                {/* <body className={inter.className}>{children}</body> */}
                <body
                    // className={`${inter.className} ${inter.variable} ${playfair_display.variable}`}
                    className={cn(
                        "min-h-screen bg-background font-inter antialiased",
                        inter.className,
                        inter.variable,
                        playfair_display.variable
                    )}
                >
                    {" "}
                    <SignedOut>
                        <SignInButton />
                    </SignedOut>
                    <SignedIn>
                        <UserButton />
                    </SignedIn>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
